apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config-api-url
 # namespace: project
  annotations:
    argocd.argoproj.io/tracking-id: my-app:/ConfigMap:project/my-app-config
  labels:
    configmap: REACT_APP_API_BASE_URL
data:
  REACT_APP_API_BASE_URL: "http://65.1.135.227:30002"
